"""Deprecated — use scripts/fix-logo-assets.py instead.

Historical note: this script once cropped a green pear mark from cheers-logo.png.
TippyMe now ships purple mark + wordmark assets regenerated by fix-logo-assets.py
from public/tippyme-logo.source.png.
"""

raise SystemExit("Use scripts/fix-logo-assets.py")
